@echo off
setlocal EnableExtensions DisableDelayedExpansion
cd /d "%~dp0"

set "ROLE=%~1"
if "%ROLE%"=="" call :choose_role

if /I not "%ROLE%"=="central" if /I not "%ROLE%"=="node" (
    echo [ERROR] Invalid role "%ROLE%". Use: launch_gml.bat central ^| node
    goto :fail
)

call :detect_python || goto :fail
if /I "%ROLE%"=="node" (
    call :check_node || goto :fail
)

call :ensure_venv || goto :fail
call ".venv\Scripts\activate.bat" || goto :fail

echo.
echo [SETUP] Updating pip...
python -m pip install --upgrade pip >nul 2>&1

if /I "%ROLE%"=="central" (
    call :pip_install "requirements-central.txt" || goto :fail
    call :load_or_create_central_env || goto :fail
    echo.
    echo [RUN] Starting CENTRAL monitor service...
    echo [RUN] Open from LAN: http://%COMPUTERNAME%:%CENTRAL_PORT%
    echo [RUN] Local health: http://localhost:%CENTRAL_PORT%/health
    set "SYNC_TOKEN=%SYNC_TOKEN%"
    set "CENTRAL_PORT=%CENTRAL_PORT%"
    python gui\central\main.py
    goto :eof
)

call :pip_install "requirements-node.txt" || goto :fail
call :install_js_assets || goto :fail
call :load_or_create_node_env || goto :fail
echo.
echo [RUN] Starting NODE uploader service...
echo [RUN] Local UI: http://localhost:8000
echo [RUN] Sync target: %SYNC_BASE_URL%
set "SYNC_BASE_URL=%SYNC_BASE_URL%"
set "SYNC_TOKEN=%SYNC_TOKEN%"
set "NODE_ID=%NODE_ID%"
python gui\backend\main.py
goto :eof

:choose_role
echo.
echo ===========================================
echo   GLOBAL MEDIA LIVE - Launcher
echo ===========================================
echo   [C] Central Monitor Server
echo   [N] Uploader Node (this PC)
echo.
choice /C CN /N /M "Select role (C/N): "
if errorlevel 2 (
    set "ROLE=node"
) else (
    set "ROLE=central"
)
exit /b 0

:detect_python
set "PY_BOOT=py -3"
%PY_BOOT% --version >nul 2>&1
if not errorlevel 1 goto :python_ok

set "PY_BOOT=python"
python --version >nul 2>&1
if not errorlevel 1 goto :python_ok

echo [ERROR] Python 3.x was not found.
echo         Install Python from https://www.python.org/downloads/windows/
echo         and enable "Add Python to PATH", then run this launcher again.
exit /b 1

:python_ok
echo [OK] Python detected via "%PY_BOOT%"
exit /b 0

:check_node
node --version >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Node.js was not found.
    echo         Install Node.js LTS from https://nodejs.org/
    exit /b 1
)

npm --version >nul 2>&1
if errorlevel 1 (
    echo [ERROR] npm was not found.
    echo         Reinstall Node.js LTS from https://nodejs.org/
    exit /b 1
)

echo [OK] Node.js and npm detected
exit /b 0

:ensure_venv
if exist ".venv\Scripts\python.exe" (
    echo [OK] Reusing existing .venv
    exit /b 0
)

echo [SETUP] Creating local virtual environment (.venv)...
%PY_BOOT% -m venv ".venv"
if errorlevel 1 (
    echo [ERROR] Failed to create .venv
    exit /b 1
)
exit /b 0

:pip_install
set "REQ_FILE=%~1"
if not exist "%REQ_FILE%" (
    echo [ERROR] Missing dependency file: %REQ_FILE%
    exit /b 1
)
echo [SETUP] Installing Python dependencies from %REQ_FILE%...
python -m pip install -r "%REQ_FILE%"
if errorlevel 1 (
    echo [ERROR] pip install failed for %REQ_FILE%
    exit /b 1
)
exit /b 0

:install_js_assets
if not exist "tiktokautouploader\Js_assets\package.json" (
    echo [ERROR] Missing JavaScript assets folder: tiktokautouploader\Js_assets
    exit /b 1
)
echo [SETUP] Installing JS dependencies (npm)...
pushd "tiktokautouploader\Js_assets"
npm install --silent
set "NPM_STATUS=%ERRORLEVEL%"
popd
if not "%NPM_STATUS%"=="0" (
    echo [ERROR] npm install failed in tiktokautouploader\Js_assets
    exit /b 1
)
exit /b 0

:ensure_config_dir
if not exist "config" mkdir "config"
if errorlevel 1 (
    echo [ERROR] Failed to create config directory
    exit /b 1
)
exit /b 0

:load_env_file
set "ENV_FILE=%~1"
if not exist "%ENV_FILE%" exit /b 0
for /f "usebackq tokens=1,* delims==" %%A in (`findstr /R /V /C:"^[ ]*#" /C:"^[ ]*$" "%ENV_FILE%"`) do (
    set "%%A=%%B"
)
exit /b 0

:load_or_create_central_env
call :ensure_config_dir || exit /b 1
set "ENV_FILE=config\central.env"
call :load_env_file "%ENV_FILE%"

if not defined SYNC_TOKEN (
    set /p SYNC_TOKEN=Enter SYNC_TOKEN for central [gml-sync-2026]:
    if "%SYNC_TOKEN%"=="" set "SYNC_TOKEN=gml-sync-2026"
)

if not defined CENTRAL_PORT (
    set /p CENTRAL_PORT=Enter central port [8100]:
    if "%CENTRAL_PORT%"=="" set "CENTRAL_PORT=8100"
)

(
    echo # Generated by launch_gml.bat
    echo SYNC_TOKEN=%SYNC_TOKEN%
    echo CENTRAL_PORT=%CENTRAL_PORT%
) > "%ENV_FILE%"

echo [OK] Saved central config to %ENV_FILE%
exit /b 0

:load_or_create_node_env
call :ensure_config_dir || exit /b 1
set "ENV_FILE=config\node.env"
call :load_env_file "%ENV_FILE%"

if not defined SYNC_BASE_URL (
    set /p SYNC_BASE_URL=Enter central URL [http://192.168.1.100:8100]:
    if "%SYNC_BASE_URL%"=="" set "SYNC_BASE_URL=http://192.168.1.100:8100"
)

if not defined SYNC_TOKEN (
    set /p SYNC_TOKEN=Enter SYNC_TOKEN (must match central) [gml-sync-2026]:
    if "%SYNC_TOKEN%"=="" set "SYNC_TOKEN=gml-sync-2026"
)

if not defined NODE_ID (
    set /p NODE_ID=Enter NODE_ID [%COMPUTERNAME%]:
    if "%NODE_ID%"=="" set "NODE_ID=%COMPUTERNAME%"
)

(
    echo # Generated by launch_gml.bat
    echo SYNC_BASE_URL=%SYNC_BASE_URL%
    echo SYNC_TOKEN=%SYNC_TOKEN%
    echo NODE_ID=%NODE_ID%
) > "%ENV_FILE%"

echo [OK] Saved node config to %ENV_FILE%
exit /b 0

:fail
echo.
echo [FAIL] Launcher stopped due to error.
pause
exit /b 1
